### PR TITLE
Merge Progressbar component

### LINKED ISSUE #114: ProgressBar
**Component**: Progress Bar

**Why this is needed**:

**What should be done**:
image

**Implementation proposal** (strongly recommended):

**Test plan**:

### PR DESCRIPTION
**Pull request by carlito-scality**
**Component**:Progressbar

**Description**:
- Merge open-source PR: https://github.com/scality/core-ui/pull/125

**Design**:
image

image

**Breaking Changes**:

- [] Breaking Changes

---

Closes: https://github.com/scality/core-ui/issues/114

### CODE REVIEW

**Comment by edumoreira1506** [comment]
Nice bro! LGTM :smile:

**Comment by carlito-scality** [comment]
> Nice bro! LGTM 😄

@edumoreira1506 Good job. Thanks :)

**Review by ChengYanJin — APPROVED** [review]
LGTM!

**Pull request merged**
