### PR TITLE
Polish navbar & sidebar 

### PR DESCRIPTION
**Pull request by ChengYanJin**
**Component**:

**Description**:
Navbar:
The non active menu item should be not bold, and set as TextTertiary
When hovered, the non-active navbar item should have the bg color set to "Highlight"
The bg color of the dropdown should be backgroundLevel1

Sidebar: 
Set background color to backgroundLevel1

**Design**:
image

**Breaking Changes**:

- [] Breaking Changes
NO

---

Closes: #ISSUE_NUMBER

### CODE REVIEW

**Review by Cuervino — COMMENTED** [review]
I don't see the bold vs non-bold font logic for the top navbar.

**Comment by ChengYanJin** [comment]
> I don't see the bold vs non-bold font logic for the top navbar.

Ha! you mean for the selected item we should set the font-weight to bold.
I thought we don't want the bold font at all for Navbar items. 

Update: c97d026541ba0edc383e913c5dbca449867d2532 should address it.

**Review by Cuervino — APPROVED** [review]
LGTM

**Pull request merged**
