### PR TITLE
Improvement - icon addition

### PR DESCRIPTION
**Pull request by Cuervino**
**Component**:

Icons set

**Description**:
 6 icons added:

- Bars
- Bound
- Unbound
- Hyphen
- Remove-circle
- Object upload

**Design**:
image

**Breaking Changes**:
No

- [] Breaking Changes

---

Closes: #ISSUE_NUMBER

### CODE REVIEW

**Review by ChengYanJin — COMMENTED** [review]
Hello @Cuervino since we are trying to have the exhaustive list,  I see two more ;D
image
image


BTW, you will need to address the `Conflicting files`. Please come to me if you need any help on this.

**Comment by Cuervino** [comment]
add Arrow-left and right

**Comment by theocerutti** [comment]
I think we should also add them to the icon wrapper.

**Review by ChengYanJin — APPROVED** [review]

**Pull request merged**
