### PR TITLE
Refact/input

### PR DESCRIPTION
**Pull request by felipebrunetti94**
**Component**:
Input

**Description**:
Refact the input component, moving the style to a new file and changing some functions.

### CODE REVIEW

**Comment by carlito-scality** [comment]
@felipebrunetti94 is this duplicated of https://github.com/scality/core-ui/pull/127?

**Review by carlito-scality — COMMENTED** [review]
@felipebrunetti94 Good idea to move Input style to a separate file. I created https://github.com/scality/core-ui/pull/133 to merge your PR due to internal process. I added some commits for improvements. Let me know if it is ok for you. Once https://github.com/scality/core-ui/pull/133, I will close your PRs. Thanks a lot

**Comment by felipebrunetti94** [comment]
@carlito-scality , it seens fine by me. You want to change something ?

**Comment by carlito-scality** [comment]
> @carlito-scality , it seens fine by me. You want to change something ?

@felipebrunetti94 perfect. I let my colleague double check my PR #133 and then we take care to merge ;) 
good job! Thanks

**Comment by felipebrunetti94** [comment]
If you want, i can refact the other components. What do you think ?

**Comment by carlito-scality** [comment]
> If you want, i can refact the other components. What do you think ?

Hi :) @felipebrunetti94 are you working on https://github.com/scality/core-ui/issues/115?

**Comment by carlito-scality** [comment]
merged in https://github.com/scality/core-ui/pull/133

**Comment by felipebrunetti94** [comment]
Hi @carlito-scality , I'm but is my first time creating svg, so it's taking some time....

**Pull request closed without merging**
