### PR TITLE
Checkbox new style

### LINKED ISSUE #311: Checkbox with new theme
**Component**:

checkbox

**Why this is needed**:

contrast is super low, making the checkbox almost not usable with the new theme
image

**What should be done**:

Update the design

**Implementation proposal** (strongly recommended):

> Hover is mouse only, focused could be with keyboard navigation.

https://www.figma.com/file/7sDg44j7bjPuojBzqLTBsV/checkboxes?node-id=0%3A1
checkboxes

### PR DESCRIPTION
**Pull request by theocerutti**
**Component**: Checkbox

**Description**: New colors for checkbox

**Design**:

image

**Breaking Changes**:

- [NO] Breaking Changes

Closes: #311

### CODE REVIEW

**Review by Cuervino — CHANGES_REQUESTED** [review]
Nice!
Just a small cursor issue > when hovering, the cursor becomes the action cursor, but after the hovered state has been loaded, it's going back to the default one, whereas it should continue to stay an "action" cursor.
Moreover, for the checked status, it looks like there is a different cursor if hovering on the 'check' mark and hovering on the rest of the checkbox.


https://user-images.githubusercontent.com/28654802/116129147-0efd0680-a6ca-11eb-9179-a640a0dc3b85.mp4

Slice 2

**Review by ChengYanJin — DISMISSED** [review]
The code LGTM!

**Review by Cuervino — APPROVED** [review]
LGTM now!

**Review by ChengYanJin — APPROVED** [review]

**Comment by theocerutti** [comment]
@bert-e approve

**Pull request merged**
