### PR TITLE
ZENKO-3273 Core-UI: fix checkbox state

### PR DESCRIPTION
**Pull request by nicolas2bert**
Disabled unchecked component renders disabled checked checkbox.

### CODE REVIEW

**Review by MonPote — APPROVED** [review]
Sorry for the very late review.
I don't have a strong opinion on this so if it's something that is require in your UI.
I'm fine with it. (and thx for updating the tests)

**Comment by nicolas2bert** [comment]
@MonPote, thank you for your review, could you please clarify what is "this" when you wrote, "I don't have a strong opinion on **this**".

**Comment by MonPote** [comment]
> @MonPote, thank you for your review, could you please clarify what is "this" when you wrote, "I don't have a strong opinion on **this**".

Forget about this comment, for some reasons I thought you change the colors. But you actually improve the `readability` of the code.

**Comment by nicolas2bert** [comment]
You probably meant `reliability` since I consider it one significant bug. 

> > @MonPote, thank you for your review, could you please clarify what is "this" when you wrote, "I don't have a strong opinion on **this**".
> 
> Forget about this comment, for some reasons I thought you change the colors. But you actually improve the `readability` of the code.

**Comment by nicolas2bert** [comment]
@bert-e approve

**Pull request merged**
