### PR TITLE
Feature/cloud progress bar

### LINKED ISSUE #124: Cloud ProgressBar
**Component**:Cloud ProgressBar

**Why this is needed**:

**What should be done**:
- We need a cloud shape progress bar in SVG with a text indicating the progress

image

**Implementation proposal** (strongly recommended):

**Test plan**:

### PR DESCRIPTION
**Pull request by ChengYanJin**
**Component**: cloudProgressBar

**Description**:
- support light/dark mode
- use CSS `keyframes` to show the animation of the cloud progress according to the percentage of input
- can customize the text inside the cloud

**Design**:
light mode:
image

dark mode:
image

---

Closes: #124

### CODE REVIEW

**Comment by ChengYanJin** [comment]
Hello @edumoreira1506,
In order to merge CloudProgressBar, I create a new branch base on yours. 
Please take a look and tell us if it's good for you.

Thanks for your contribute!

**Comment by edumoreira1506** [comment]
Nice! LGTM

**Review by carlito-scality — APPROVED** [review]
Good job @edumoreira1506 @ChengYanJin :)

**Pull request merged**
